### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by hidden-nickname** [nihilus/snowman#31]
Hello!

I'm interesting  on MIPS decompiler.
All code compiled fine from current version, but when I tested it on MIPS ELF files from 
https://github.com/nihilus/snowman-tests/tree/master/mipsbin
allication crashed.

For example,
~/snowman/snowman-tests/mipsbin$ nocode auto_wan_pt 
nocode: [path skipped]/snowman/src/nc/arch/mips/MipsInstructionAnalyzer.cpp:1110: std::unique_ptrcore::ir::Term nc::arch::mips::MipsInstructionAnalyzerImpl::createTermForOperand(std::size_t, SmallBitSize) const: Проверочное утверждение «!"Unreachable code executed."» не выполнено.

Thanks.

**Comment by techbliss** [comment]
I cant get it to crash on the auto_wan_pt.
However this build is a week old.

![ggqzi](https://cloud.githubusercontent.com/assets/3592375/9549838/535e5b52-4da8-11e5-9327-03641f7dca67.jpg)

**Comment by nihilus** [comment]
@hidden-nickname That is typically a GCC bug with -O2. Change to -O and it Will probably work.

**Comment by nihilus** [comment]
hmm interesting... :-/

**Comment by nihilus** [comment]
```
Invalid instruction `beqz $v0, 0x400b90' at 0x400b64: The instruction does not have an argument with index 0
[Warning] Invalid instruction `beq $v0, $v1, 0x400cc4' at 0x400cac: The instruction does not have an argument with index 1
```

**Comment by nihilus** [comment]
@hidden-nickname try build it using CLang.
And be aware that I am about to fix the ELF parsing; since like most people know it is kinda quirky on MIPS.

**Comment by hidden-nickname** [comment]
What I doing:
mkdir build
cd build
CXX=clang cmake ../src
cmake --build .

[output skipped]
[ 98%] Building CXX object nocode/CMakeFiles/nocode.dir/main.cpp.o
[ 99%] Building CXX object nocode/CMakeFiles/nocode.dir/nocode_automoc.cpp.o
Linking CXX executable nocode
/usr/bin/ld: CMakeFiles/nocode.dir/main.cpp.o: неопределённая ссылка на символ «__cxa_free_exception@@CXXABI_1.3»
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [nocode/nocode] Ошибка 1
make[1]: **\* [nocode/CMakeFiles/nocode.dir/all] Ошибка 2
make: **\* [all] Ошибка 2

Looks like something missing or wrong library path, but I don't know where (sorry, I'm newbie in C and so on languages).

**Comment by nihilus** [comment]
First 'cd src' then 'cmake .' then 'ccmake .'
ccmake (notice the extra 'c') is for configuring CC and CXX and so on with cmake.

And please use 'make' to build it after invoking cmake.

**Comment by hidden-nickname** [comment]
Till fail with cmake:
[ 98%] Building CXX object nocode/CMakeFiles/nocode.dir/main.cpp.o
[ 99%] Building CXX object nocode/CMakeFiles/nocode.dir/nocode_automoc.cpp.o
Linking CXX executable nocode
/usr/bin/ld: CMakeFiles/nocode.dir/main.cpp.o: неопределённая ссылка на символ «__cxa_free_exception@@CXXABI_1.3»
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [nocode/nocode] Ошибка 1
make[1]: **\* [nocode/CMakeFiles/nocode.dir/all] Ошибка 2
make: **\* [all] Ошибка 2

and with make:
[ 98%] Automoc for target nocode
[ 98%] Built target nocode_automoc
Linking CXX executable nocode
/usr/bin/ld: CMakeFiles/nocode.dir/main.cpp.o: неопределённая ссылка на символ «__cxa_free_exception@@CXXABI_1.3»
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [nocode/nocode] Ошибка 1
make[1]: **\* [nocode/CMakeFiles/nocode.dir/all] Ошибка 2
make: **\* [all] Ошибка 2

:(

**Comment by techbliss** [comment]
building in prompt fail here also, but vs does the trick for me.
for VS2013

Cmake configure:

```
cmake -G "Visual Studio 12" -D -DCMAKE_BUILD_TYPE=Release -D QT_NAMESPACE=QT -D IDA_PLUGIN_ENABLED=YES -D IDA_64_BIT_EA_T=NO -D NC_QT5=NO ../src
```

then 
continue build in vs.
remember to make only release.

**Comment by hidden-nickname** [comment]
@techbliss 
Thank you, but I'm not have Visual Studio. I'm not windows user.

**Comment by nihilus** [comment]
@hidden-nickname @techbliss this work flawless on OS X:

```
zarathustra:src nietzsche$ clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

so if @hidden-nickname would want to contribute with a patch she is welcome. If not she is on her own.

**Comment by hidden-nickname** [comment]
Hmmm...
I'll try to compile and when check results on snowman-tests/mipsbin.

g++ and gcc (compiled with make and cmake) = application crash on test;
clang++ and clang (v. 3.4 compiled with make and cmake) = appilation crash on test;
clang++ and clang (v. 3.8 compiled with make and cmake) = appilation crash on test;

Someone have running application on linux (ubuntu for example)?

P.S.
QT5, boost headers - 1.54, clang - 3.8 (was 3.4), gcc - 4.8.4, libstdc++ - 4.4 (and 4.4.7), cmake - 2.8.12.2

**Comment by nihilus** [comment]
Hmm I use QT4 fwiw

**Comment by hidden-nickname** [comment]
@nihilus Ok, i'll try with QT4, but I think it can't help me, becouse I run non-qt application - nocode.

qt4 and g++/gcc (with make) = application crash on test

**Comment by nihilus** [comment]
Actually nocode is a QT application without GUI.

**Comment by nihilus** [comment]
@hidden-nickname does it work with the ARM binaries?

**Comment by hidden-nickname** [comment]
@nihilus  ARM binaries works fine, all as expected.
Today I try to check on Debian system. I hope that everything will work as it should.

Updated:
Debian 8 x64, QT5, libboost 1.55, clang 3.5.0, cmake 3.0.2, gcc 4.9.2, libstdc++ 4.9 - same story with gcc and clang compiler :(

**Comment by nihilus** [comment]
Could you guys test with the latest revision. It fixes some bugs and introduce new ones.

**Comment by hidden-nickname** [comment]
@nihilus 
Ok. I'll test new revision. 

Updated:
The same...
~/snowman-mips/snowman-tests/mipsbin$ nocode auto_wan_pt
nocode: [homedir skipped]/snowman-mips/snowman/src/nc/arch/mips/MipsInstructionAnalyzer.cpp:1164: std::unique_ptrcore::ir::Term nc::arch::mips::MipsInstructionAnalyzerImpl::createTermForOperand(std::size_t, SmallBitSize) const: Assertion `!"Unreachable code executed."' failed.
Aborted (core dumped)

But I can't find coredump.

Update 2:
Linux Mint 17.2 (32 bit) - same story :(

Anyone run this application under Linux?

**Comment by nihilus** [comment]
@hidden-nickname I got the same issues here at work on Ubuntu 12.x LTS.

**Comment by nihilus** [comment]
@hidden-nickname try 

```
cmake src  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
```

if not specified like this cmake will fallback on your default CXX.
To verifiy the compiler run

```
make VERBOSE=1
```

**Comment by nihilus** [comment]
@hlide we've got an issue with Linux here and the delayslotCallback... For reasons unknown it does not play well with Linux's libstdc++.

```
        case MIPS_INS_BEQZ: {
            auto block = MipsExpressionFactoryCallback(factory_, program->createBasicBlock(), instruction);
            auto taken = delayslotCallback(block)[
                             jump(operand(1))
            ];
            _[
                jump((operand(0) == constant(0)),
                     taken.basicBlock(),
                     directSuccessor())
            ];
            break;
        }
```

will crash when it tries to do the jump containing the evaluated delayslot and the expression within it. Any clues?

**Comment by techbliss** [comment]
yep it crrashed also on my test build on kali linux distro.

but examing the verbose error.

```
[ 56%] Building CXX object nc/arch/mips/CMakeFiles/nc-arch-mips.dir/MipsInstructionAnalyzer.cpp.o
cd /root/Skrivebord/snowman-master/nc/arch/mips && /usr/bin/gcc   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -O3 -DNDEBUG -std=c++11 -O2 -g -DNDEBUG -I/root/Skrivebord/snowman-master/src -I/root/Skrivebord/snowman-master/src/3rd-party -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtGui -isystem /usr/include/qt4/QtCore -I/root/Skrivebord/snowman-master    -Wall -Wextra -fshow-column -fno-strict-aliasing -Wno-strict-overflow -Wno-maybe-uninitialized -o CMakeFiles/nc-arch-mips.dir/MipsInstructionAnalyzer.cpp.o -c /root/Skrivebord/snowman-master/src/nc/arch/mips/MipsInstructionAnalyzer.cpp
gcc: internal compiler error: Dræbt (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
nc/arch/mips/CMakeFiles/nc-arch-mips.dir/build.make:110: recipe for target 'nc/arch/mips/CMakeFiles/nc-arch-mips.dir/MipsInstructionAnalyzer.cpp.o' failed
make[2]: *** [nc/arch/mips/CMakeFiles/nc-arch-mips.dir/MipsInstructionAnalyzer.cpp.o] Error 4
make[2]: Leaving directory '/root/Skrivebord/snowman-master'
CMakeFiles/Makefile2:194: recipe for target 'nc/arch/mips/CMakeFiles/nc-arch-mips.dir/all' failed
make[1]: *** [nc/arch/mips/CMakeFiles/nc-arch-mips.dir/all] Error 2
make[1]: Leaving directory '/root/Skrivebord/snowman-master'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

the error seems to be in makefile2 line 194.
since makefile line 138 leads to makefile2

makefile2 194:

```
$(MAKE) -f nc/arch/mips/CMakeFiles/nc-arch-mips.dir/build.make nc/arch/mips/CMakeFiles/nc-arch-mips.dir/depend
```

leads to 

```
/snowman-master/nc/arch/mips/CMakeFiles/nc-arch-mips.dir/depend.make
```

there is the dependicies needed to buils mips, and error indicates its missing or cant find them.
im guessing PyQt LIB and INCLUDE.
here is full list of dependicies
http://pastebin.com/HP3fK3qD

maybe check also Dependinfo.cmake from same folder.

**Comment by nihilus** [comment]
@techbliss guess you should use g++ instead of gcc.

**Comment by techbliss** [comment]
can confirm 

```
cmake src  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
```

if not specified like this cmake will fallback on your default CXX.
To verifiy the compiler run

```
make VERBOSE=1
```

builds fine but error when loading mips on linux

**Comment by techbliss** [comment]
mmhh if you hook of decompile automateclly before open file it works on the auto_wan_pt , but some line fail

**Comment by nihilus** [comment]
Seems like something messes up the recursion in createStatement() when called from the delayslotCallback().

**Comment by nihilus** [comment]
Actually it is the use of 'tmpdetail_' that makes it crash. :(

**Comment by nihilus** [comment]
@hlide do you have any clues how to store/restore 'detail_' when calling the delaySlotCallback()?

**Comment by hlide** [comment]
``` c++
auto delayslot = [&](MipsExpressionFactoryCallback & callback) -> MipsExpressionFactoryCallback & {
    auto detail = detail_;
    auto delayslot = checked_cast<const MipsInstruction *>(instructions_->get(instruction->endAddr()).get());
    if (delayslot) {
        createStatements(callback, delayslot, program);
    }
    else {
        throw core::irgen::InvalidInstructionException(tr("Cannot find a delay slot at 0x%1.").arg(instruction->endAddr(), 0, 16));
    }
    detail_ = detail;
    return callback;
};
```

**Comment by nihilus** [comment]
@hlide Except for 'auto' I dont see this different from the current implementation. I tried fixing it with auto but the recursive call seems to mess up 'detail' in your example. :-/ NB it seems to work fine on both Windows and OS X.

**Comment by hlide** [comment]
as long as _detail_ is a local variable (i.e, in a stack), it should be fine.

**Comment by hlide** [comment]
it crashes because _details__ points upon a freed pointer?

**Comment by hlide** [comment]
do you have _instr__?

**Comment by hlide** [comment]
In my repository, I commented it:

``` c++
class MipsInstructionAnalyzerImpl {
    Q_DECLARE_TR_FUNCTIONS(MipsInstructionAnalyzerImpl)

    const MipsArchitecture *architecture_;
    core::arch::Capstone capstone_;
    MipsExpressionFactory factory_;
    core::ir::Program *program_;
    const MipsInstruction *instruction_;
    //core::arch::CapstoneInstructionPtr instr_;
    const cs_mips *detail_;
    const core::arch::Instructions *instructions_;
...
```

I think when _delaySlot_ is called, _createStatement_ is replacing _instr__ (so the previous is deleted due to _std::unique_prt<>_ rules, and so is the previous _instr_->detail_. So when reassigning _detail_, you got a pointer on a deleted one.

**Comment by hlide** [comment]
Maybe it will work with:

``` c++
auto delayslot = [&](MipsExpressionFactoryCallback & callback) -> MipsExpressionFactoryCallback & {
    auto instr = instr_;
    auto delayslot = checked_cast<const MipsInstruction *>(instructions_->get(instruction->endAddr()).get());
    if (delayslot) {
        createStatements(callback, delayslot, program);
    }
    else {
        throw core::irgen::InvalidInstructionException(tr("Cannot find a delay slot at 0x%1.").arg(instruction->endAddr(), 0, 16));
    }
    instr_ = instr;
    detail_ = instr->detail;
    return callback;
};
```

**Comment by nihilus** [comment]
@hilde: Interesting:
```
 62%] Building CXX object nc/arch/mips/CMakeFiles/nc-arch-mips.dir/MipsInstructionAnalyzer.cpp.o
/Users/nietzsche/Downloads/snowman/src/nc/arch/mips/MipsInstructionAnalyzer.cpp:105:13: error: 
      call to implicitly-deleted copy constructor of 'std::__1::unique_ptr<cs_insn,
      nc::core::arch::CapstoneDeleter>'
                auto instr = instr_;
                     ^       ~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2510:31: note: 
      copy constructor is implicitly deleted because 'unique_ptr<cs_insn,
      nc::core::arch::CapstoneDeleter>' has a user-declared move constructor
    _LIBCPP_INLINE_VISIBILITY unique_ptr(unique_ptr&& __u) _NOEXCEPT
                              ^
1 error generated.
```

**Comment by nihilus** [comment]
Seems to be fixed in my last commit according to my Ubuntu VM. Thx @hlide 
Could you verify this @hidden-nickname ?

**Comment by hidden-nickname** [comment]
Wow!
With latest commit 88b8854ef6 auto_wan\* file (and some other) decompiled fine (project compiled with clang++ and clang).

But on fsn file... 
$ snowman --verbose fsn 
Illegal instruction (core dumped)

and no additional info.

**Comment by nihilus** [comment]
@hidden-nickname fsn is not an O32 ABI ELF file but N32 IRIX ABI ELF file which is not yet supported.

**Comment by hidden-nickname** [comment]
@nihilus Sorry :)
I'll check more binaries, if you want.

**Comment by nihilus** [comment]
Ive checked them all already :-)

**Comment by hidden-nickname** [comment]
Hmm... Testing on Kernel Module (*.ko file) with ELF header. 

nocode --verbose ath_dev.ko 
[Info] Choosing a parser for ath_dev.ko...
[Info] Trying ELF parser...
[Info] Parsing using ELF parser...
[Info] Parsing completed.
[Info] Disassemble code sections.
[Info] Disassemble section ...
[Info] Disassemble addresses from 0x0 to 0x35490...
[Info] Disassembly completed.
[Info] Disassemble section ...
[Info] Disassemble addresses from 0x0 to 0x14...
[Info] Disassembly completed.
[Info] Disassemble section ...
[Info] Disassemble addresses from 0x0 to 0x1ac...
[Info] Disassembly completed.
[Info] Decompiling.
[Info] Creating intermediate representation of the program.
Illegal instruction (core dumped)

or

$ snowman ath_dev.ko 
Illegal instruction (core dumped)

Where can I put this file for testing?

**Comment by nihilus** [comment]
@hidden-nickname: try to debug it with gdb please.

**Comment by hidden-nickname** [comment]
$ gdb --args nocode --verbose ath_dev.ko
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nocode...done.
(gdb) run
Starting program: /usr/local/bin/nocode --verbose ath_dev.ko
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Info] Choosing a parser for ath_dev.ko...
[Info] Trying ELF parser...
[Info] Parsing using ELF parser...
[Info] Parsing completed.
[Info] Disassemble code sections.
[Info] Disassemble section ...
[Info] Disassemble addresses from 0x0 to 0x35490...
[Info] Disassembly completed.
[Info] Disassemble section ...
[Info] Disassemble addresses from 0x0 to 0x14...
[Info] Disassembly completed.
[Info] Disassemble section ...
[Info] Disassemble addresses from 0x0 to 0x1ac...
[Info] Disassembly completed.
[Info] Decompiling.
[Info] Creating intermediate representation of the program.

Program received signal SIGSEGV, Segmentation fault.
nc::core::ir::Term::clone (this=0x0)
    at /home/vitaly/decompilers/snowman/src/nc/core/ir/Term.h:148
148     std::unique_ptr<Term> clone() const { return doClone(); }
(gdb) 

Looks like tripple start address ( from 0x0 )

**Comment by nihilus** [comment]
NULL-ptr reference.
