### ISSUE TITLE
prebuild files

### ISSUE THREAD

**Issue by dpeddi** [nihilus/snowman#44]
do you have prebuild files?

windows/ida

Regards

**Comment by nihilus** [comment]
For which platform?

**Comment by dpeddi** [comment]
if possible, windows exe and ida windows plugin

**Comment by nihilus** [comment]
For that I recommend that you vista my friend @techbliss and his forum at: http://www.techbliss.org/threads/ida-pro-smartdec-decompiler-source-released.689/

**Comment by dpeddi** [comment]
thank you... actually techbliss seems to have prebuild binaries dated 2015-10-01 that miss your latest  changes that sound interesting...

**Comment by nihilus** [comment]
Ask politely and @techbliss will build new ones. :-)

**Comment by techbliss** [comment]
@dpeddi  can build one after work today

**Comment by techbliss** [comment]
Okay here is x86 build with zlib the the extra parser that was pushed the last days.
Im not sure if the x64 code is fixed for ida yet. 
http://www.techbliss.org/threads/ida-pro-smartdec-decompiler-source-released.689/#post-2572

**Comment by techbliss** [comment]
nope the ida 64 one crashes on testfiles

**Comment by nihilus** [comment]
Hmm... Yeah, I vent dug down into fixing 64 bits on windows.

**Comment by nihilus** [comment]
You should try put the prereleased one.

**Comment by Manouchehri** [comment]
@nihilus Got any Linux `.plx64` and `.plx` binaries floating around? Finding it a bit challenging to get it to build.

**Comment by nihilus** [comment]
Might try to build it during weekend. However I am not sure  about how to get QT right etc. for Linux.
