### ISSUE TITLE
Cannot build Ninja

### ISSUE THREAD

**Issue by ghost** [nihilus/snowman#62]
I cannot get Ninja to build in Cygwin. I need an alternative to build snowman.

~/nihilus-snowman-master/snowman-master
$ make -f makefile
ctags --c++-kinds=+p --fields=+iaS --extra=+q -R /home/adbal/nihilus-snowman-master/snowman-master/src
cd /tmp/snowman.102ae12bc5eadf8c353cc9df86e00f1dce03ab95 && cmake -G Ninja /home/adbal/nihilus-snowman-master/snowman-master/src
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** [makefile:21: /tmp/snowman.102ae12bc5eadf8c353cc9df86e00f1dce03ab95/build.ninja] Error 1

**Comment by ghost** [comment]
Nevermind, I realized that I overlooked the build.asciidoc....

**Comment by nihilus** [comment]
Please dont bug me or anyone else with build issues on Cygwin.
